# Generated by Django 5.2 on 2025-04-14 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaClassOccurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('is_canceled', models.BooleanField(default=False)),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('yoga_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occurrences', to='studio.yogaclass')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('yoga_class', 'date')},
            },
        ),
    ]
