# Generated by Django 5.2 on 2025-04-15 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studio', '0002_yogaclassoccurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='occurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='studio.yogaclassoccurrence'),
        ),
    ]
